name: regenerate feed
on:
  schedule:
    - cron: '5 13 * * *'   # every day at 13:05 UTC ≈ 6:05 PT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install feedparser PyRSS2Gen
      - run: python rssgenerator.py
      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add customfeed.xml
          git commit -m "auto: refresh feed" || echo "No changes"
          git push
